---
# tasks file for outline
- name: Set up main directory
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "{{ ansible_effective_user_id }}"
    group: "{{ ansible_effective_group_id }}"
    mode: "0750"
  with_items:
    - "{{ outline_setup_path }}"
  tags:
    - configuration
  become: true

- name: Set up config directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "{% if outline_uid %}{{ outline_uid }}{% else %}{{ ansible_effective_user_id }}{% endif %}"
    group: "{% if outline_gid %}{{ outline_gid }}{% else %}{{ ansible_effective_group_id }}{% endif %}"
    mode: "0750"
  with_items:
    - "{{ outline_setup_path | expanduser | realpath }}"
    - "{{ outline_volume_redis | expanduser | realpath }}"
    - "{{ outline_volume_s3 | expanduser | realpath }}"
  tags:
    - configuration
  become: true

- name: Set up the database directory.
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: "0755"
    owner: 70
  with_items:
    - "{{ outline_volume_db | expanduser | realpath }}"
  tags:
    - configuration
  become: true

- name: Write configuration files
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ outline_setup_path | expanduser | realpath }}/{{ item }}"
    mode: '0640'
  loop:
    - "docker-compose.yml"
    - "env.outline.conf"
    - "env.db.conf"
    - "env.oidc.conf"
    - "env.redis.conf"
    - "env.s3.conf"
  tags:
    - configuration

- name: Ensure all requested components are running.
  community.docker.docker_compose_v2:
    project_src: "{{ outline_setup_path | expanduser | realpath }}"
    build: false
  become: false
